# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Install build dependencies
      run: |
        go get github.com/mitchellh/gox@latest
        go install github.com/mitchellh/gox@latest

    - name: Build
      run: gox -os="linux darwin windows" -arch="amd64" -ldflags "-s" -verbose ./...

    - name: Test
      run: go test -v ./...
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          pcd_windows_amd64.exe
          pcd_darwin_amd64
          pcd_linux_amd64
